/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as PalavrasChaveRouteImport } from './routes/palavras-chave'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ConcursosRouteImport } from './routes/concursos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoIdRouteImport } from './routes/historico.$id'

const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const PalavrasChaveRoute = PalavrasChaveRouteImport.update({
  id: '/palavras-chave',
  path: '/palavras-chave',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursosRoute = ConcursosRouteImport.update({
  id: '/concursos',
  path: '/concursos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoIdRoute = HistoricoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoricoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concursos': typeof ConcursosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/palavras-chave': typeof PalavrasChaveRoute
  '/pesquisa': typeof PesquisaRoute
  '/historico/$id': typeof HistoricoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concursos': typeof ConcursosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/palavras-chave': typeof PalavrasChaveRoute
  '/pesquisa': typeof PesquisaRoute
  '/historico/$id': typeof HistoricoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concursos': typeof ConcursosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/palavras-chave': typeof PalavrasChaveRoute
  '/pesquisa': typeof PesquisaRoute
  '/historico/$id': typeof HistoricoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concursos'
    | '/configuracoes'
    | '/historico'
    | '/login'
    | '/onboarding'
    | '/palavras-chave'
    | '/pesquisa'
    | '/historico/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concursos'
    | '/configuracoes'
    | '/historico'
    | '/login'
    | '/onboarding'
    | '/palavras-chave'
    | '/pesquisa'
    | '/historico/$id'
  id:
    | '__root__'
    | '/'
    | '/concursos'
    | '/configuracoes'
    | '/historico'
    | '/login'
    | '/onboarding'
    | '/palavras-chave'
    | '/pesquisa'
    | '/historico/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConcursosRoute: typeof ConcursosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PalavrasChaveRoute: typeof PalavrasChaveRoute
  PesquisaRoute: typeof PesquisaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palavras-chave': {
      id: '/palavras-chave'
      path: '/palavras-chave'
      fullPath: '/palavras-chave'
      preLoaderRoute: typeof PalavrasChaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concursos': {
      id: '/concursos'
      path: '/concursos'
      fullPath: '/concursos'
      preLoaderRoute: typeof ConcursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$id': {
      id: '/historico/$id'
      path: '/$id'
      fullPath: '/historico/$id'
      preLoaderRoute: typeof HistoricoIdRouteImport
      parentRoute: typeof HistoricoRoute
    }
  }
}

interface HistoricoRouteChildren {
  HistoricoIdRoute: typeof HistoricoIdRoute
}

const HistoricoRouteChildren: HistoricoRouteChildren = {
  HistoricoIdRoute: HistoricoIdRoute,
}

const HistoricoRouteWithChildren = HistoricoRoute._addFileChildren(
  HistoricoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConcursosRoute: ConcursosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PalavrasChaveRoute: PalavrasChaveRoute,
  PesquisaRoute: PesquisaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
